services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    Elasticsearch:
        image: elasticsearch:8.9.0
        container_name: elasticsearch
        restart: always
        volumes:
            - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            discovery.type: single-node
        ports:
            - '9200:9200'
            - '9300:9300'
        networks:
            - sail

    Logstash:
        image: logstash:8.9.0
        container_name: logstash
        restart: always
        volumes:
            - ./docker/logstash/:/logstash_dir
        command: logstash -f /logstash_dir/logstash.conf
        depends_on:
            - Elasticsearch
        ports:
            - '9600:9600'
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - sail

    Kibana:
        image: kibana:8.9.0
        container_name: kibana
        restart: always
        volumes:
            - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
            - '5601:5601'
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - ELASTICSEARCH_HOSTS=http://localhost:9200
        depends_on:
            - Elasticsearch
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
