import 'bootstrap/dist/css/bootstrap.css'
import '%/css/style.css';
import '%/css/responsive.css';
import { Providers } from "$/providers";


import ScrollToTop from "@/layouts/ScrollToTop";
import React from "react";

export const metadata = {
    title: 'Taraznir',
    description: 'Generated by create next app',
    viewport:'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
        <ScrollToTop />
      </body>
    </html>
  )
}

