import 'bootstrap/dist/css/bootstrap.css'
import '%/css/style.css';
import '%/css/responsive.css';
import { Providers } from "$/providers";


import ScrollToTop from "@/layouts/ScrollToTop";
import React from "react";

export const metadata = {
    title: 'Taraznir',
    description: 'Generated by create next app',
    viewport:'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
                <link href="https://fonts.googleapis.com/css2?family=Jost:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
                <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
                <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet"/>
            </head>
            <body>
                <Providers>
                {children}
                </Providers>
                <ScrollToTop />
            </body>
        </html>
    )
}

