import 'bootstrap/dist/css/bootstrap.css'
import '%/css/style.css';
import '%/css/responsive.css';
import { Providers } from "$/providers";


import ScrollToTop from "@/layouts/ScrollToTop";
import React, {use} from "react";
import {ThemeType} from "^/ThemeType";
import {getTheme} from "#/getTheme";
import Header from "@/layouts/Header";
import Footer from "@/layouts/Footer";
import Sidebar from "@/layouts/Sidebar";

export const metadata = {
    title: 'Taraznir',
    description: 'Generated by create next app',
    viewport:'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

    const themeOptions:ThemeType = use(getTheme('_theme' ));
    console.log(themeOptions)
    return (
        <html lang="en">
            <head>
                <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
                <link href="https://fonts.googleapis.com/css2?family=Jost:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
                <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
                <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet"/>
            </head>
            <body>
                <div className="page-wrapper">
                    <Providers>
                        <Header options={themeOptions}/>
                        {children}
                        <ScrollToTop />
                        <Footer options={themeOptions}/>
                        <Sidebar/>
                    </Providers>
                </div>
            </body>
        </html>
    )
}

